# Site settings
name: Less Or More
email: wangzshy@sina.com
author: Wang Zheng
url: 
resume_site: 
github: https://github.com/
baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wangzshy

# Build settings
markdown: kramdown

baidu_analysis: 

