# Site settings
name: wz's blog
email: wangzshy@sina.com
author: wz
url: https://wangzshy.github.io/
resume_site: 
github: https://github.com/wangzshy/
baseurl: "/"
description: Actually, less is more!
meta_description: 知而不惑，不惑而不忧不怨
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: wangzshy

# Build settings
markdown: kramdown

baidu_analysis: 

